services:
    rabbitmq:
        image: rabbitmq:3.9-management
        ports:
            - '5672:5672'
            - '15672:15672'
        networks:
            - app-network

    gateway:
        build: ./gateway
        ports:
            - '3000:3000'
        networks:
            - app-network

    user-service:
        build: ./user-service
        ports:
            - '3001:3001'
        networks:
            - app-network

    status-service:
        build: ./status-service
        ports:
            - '3002:3002'
        networks:
            - app-network

    course-service:
        build: ./course-service
        ports:
            - '3003:3003'
        networks:
            - app-network

    tags-service:
        build: ./tags-service
        ports:
            - '3004:3004'
        networks:
            - app-network

    lesson-service:
        build: ./lesson-service
        ports:
            - '3005:3005'
        networks:
            - app-network

    comments-service:
        build: ./comments-service
        ports:
            - '3006:3006'
        networks:
            - app-network

    enrollment-service:
        build: ./enrollment-service
        ports:
            - '3007:3007'
        networks:
            - app-network
            
networks:
    app-network:
        driver: bridge